version: '3'
services:
  cv:
    build:
      context: .
      dockerfile: Dockerfile
      target: release
    volumes:
      - .:/opt/app

  worker:
    depends_on:
      - cv
    image: nginx:latest
    #deploy:
    #  replicas: 3
    volumes:
      - ./config/nginx/worker.conf:/etc/nginx/conf.d/default.conf
      - .:/usr/share/nginx/html

  balancer:
    depends_on:
      - worker
    ports:
      - 8080:80
    image: nginx:latest
    volumes:
      - ./config/nginx/balancer.conf:/etc/nginx/conf.d/default.conf